server:
    port: 9099
  
spring: 
  datasource:
         url: jdbc:mysql://localhost:3306/ssn_app
         driver-class-name: com.mysql.cj.jdbc.Driver
         username: root
         password: root
  jpa:
     hibernate:
            ddl-auto: update 
     properties:
           hibernate:
             show-sql: true 
             format-sql: true
             
     database-platform: org.hibernate.dialect.MySQL8Dialect        
             